### PR TITLE
[routing] Add custom blocking & bypass sites routing rules

### PR DESCRIPTION
**Pull request by dexfire**
There are conditions the site not matches the rules from the ready-up ruleSets, or we need different behaviour. We can add via custom blocking & bypass routing rules now.

NOTE: DNS rule not handled.

### CODE REVIEW

**Review by dexfire — COMMENTED** [review]
no err found

**Comment by bia-pain-bache** [comment]
Thanks, but the _worker.js is the built code, the source code is src/worker.js.
Apparently I should provide a instruction for it...

**Comment by dexfire** [comment]
- [x] singbox verified ok
 - [x] xray test [ only gramma verified, no real test]
 - [x] clash test [only gramma verified, no real test]

**Comment by dexfire** [comment]
> Thanks, but the _worker.js is the built code, the source code is src/worker.js. Apparently I should provide a instruction for it...

I realized that finally after update the _worker.js, i'm not a pro js coder...
and now the worker.js have updated.

**Review by dexfire — COMMENTED** [review]
no err found

**Comment by bia-pain-bache** [comment]
The contributions make pros not skills ;) tnx btw.

**Comment by dexfire** [comment]
> The contributions make pros not skills ;) tnx btw.
just add what i need ^v^. a good project first.

**Comment by bia-pain-bache** [comment]
I will implement it soon, It was in middle of restructuring the whole code.

**Comment by bia-pain-bache** [comment]
The feature is implented from scratch in 2.7.3, please check details. Thanks for your contribution again.

**Pull request closed without merging**
