### PR TITLE
Added obfuscation to solve 1101 error

### PR DESCRIPTION
**Pull request by shulng**

### CODE REVIEW

**Comment by shulng** [comment]
@bia-pain-bache

**Comment by bia-pain-bache** [comment]
Really appreciate your contribution, I merge it with some subtle changes.

**Comment by shulng** [comment]
> Really appreciate your contribution, I merge it with some subtle changes.

npm install -g javascript-obfuscator
It needs to be in actions, otherwise the command cannot be found.

**Comment by shulng** [comment]
@bia-pain-bache

**Comment by aiinit** [comment]
still happen 1101 error in today.

**Comment by shulng** [comment]
> still happen 1101 error in today.

试试这个[_worker.js](https://raw.githubusercontent.com/lu-lingyun/BPB-Worker-Panel/refs/heads/dev/_worker.js)

**Comment by aiinit** [comment]
> > still happen 1101 error in today.
> 
> 试试这个[_worker.js](https://raw.githubusercontent.com/lu-lingyun/BPB-Worker-Panel/refs/heads/dev/_worker.js)

问题依旧，感觉是我的账号被特别对待了，我有几个号，就某一个怎么建都都1101错误。

**Comment by shulng** [comment]
> 仍然存在 1101 错误

#536

**Comment by shulng** [comment]
> > 仍然存在 1101 错误
> 
> #536

@aiinit @vahidikhan

**Pull request merged**
